// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace alertingSystemBackend.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20260205151753_BackendCreation")]
    partial class BackendCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("alertingSystemBackend.Models.Entities.Alert", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Criticite")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateEscaladeN1")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateEscaladeN2")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateNotification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DatePriseEnCharge")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateResolution")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NiveauEscaladeActuel")
                        .HasColumnType("integer");

                    b.Property<long>("ResponsableActuelId")
                        .HasColumnType("bigint");

                    b.Property<long>("SourceId")
                        .HasColumnType("bigint");

                    b.Property<int>("StatutAlert")
                        .HasColumnType("integer");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TypeAlerte")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ResponsableActuelId");

                    b.ToTable("Alertes");
                });

            modelBuilder.Entity("alertingSystemBackend.Models.Entities.ConfigurationEscalade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("DelaiNiveau0VersNiveau1")
                        .HasColumnType("integer");

                    b.Property<int>("DelaiNiveau1VersNiveau2")
                        .HasColumnType("integer");

                    b.Property<int>("FrequenceVerification")
                        .HasColumnType("integer");

                    b.Property<int>("IntervalleRappel")
                        .HasColumnType("integer");

                    b.Property<int>("NombreRappelsMax")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ConfigurationsEscalade");
                });

            modelBuilder.Entity("alertingSystemBackend.Models.Entities.Escalade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AlerteId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateEscalade")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DeclenchementAutomatique")
                        .HasColumnType("boolean");

                    b.Property<int>("NiveauArrivee")
                        .HasColumnType("integer");

                    b.Property<int>("NiveauDepart")
                        .HasColumnType("integer");

                    b.Property<long>("NotificationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Raison")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Escalades");
                });

            modelBuilder.Entity("alertingSystemBackend.Models.Entities.Historique", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("AlerteId")
                        .HasColumnType("bigint");

                    b.Property<int>("AncienStatut")
                        .HasColumnType("integer");

                    b.Property<string>("Commentaire")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateAction")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NouveauStatut")
                        .HasColumnType("integer");

                    b.Property<long>("UtilisateurId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AlerteId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Historiques");
                });

            modelBuilder.Entity("alertingSystemBackend.Models.Entities.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AlerteId")
                        .HasColumnType("bigint");

                    b.Property<int>("Canal")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateEnvoi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateLecture")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DestinataireId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Envoyee")
                        .HasColumnType("boolean");

                    b.Property<bool>("Lue")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Priorite")
                        .HasColumnType("integer");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TypeNotification")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlerteId");

                    b.HasIndex("DestinataireId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("alertingSystemBackend.Models.Entities.Planificateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DerniereExecution")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IntervalVerification")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Planificateurs");
                });

            modelBuilder.Entity("alertingSystemBackend.Models.Entities.RegleEscalade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int>("Criticite")
                        .HasColumnType("integer");

                    b.Property<int>("DelaiAvantEscalade")
                        .HasColumnType("integer");

                    b.Property<int>("NiveauCible")
                        .HasColumnType("integer");

                    b.Property<int>("NiveauSource")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TypeAlerte")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ReglesEscalade");
                });

            modelBuilder.Entity("alertingSystemBackend.Models.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Actif")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("alertingSystemBackend.Models.Entities.Alert", b =>
                {
                    b.HasOne("alertingSystemBackend.Models.Entities.User", "ResponsableActuel")
                        .WithMany()
                        .HasForeignKey("ResponsableActuelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResponsableActuel");
                });

            modelBuilder.Entity("alertingSystemBackend.Models.Entities.Historique", b =>
                {
                    b.HasOne("alertingSystemBackend.Models.Entities.Alert", "Alerte")
                        .WithMany()
                        .HasForeignKey("AlerteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("alertingSystemBackend.Models.Entities.User", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alerte");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("alertingSystemBackend.Models.Entities.Notification", b =>
                {
                    b.HasOne("alertingSystemBackend.Models.Entities.Alert", "Alerte")
                        .WithMany()
                        .HasForeignKey("AlerteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("alertingSystemBackend.Models.Entities.User", "Destinataire")
                        .WithMany()
                        .HasForeignKey("DestinataireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alerte");

                    b.Navigation("Destinataire");
                });
#pragma warning restore 612, 618
        }
    }
}
